app/mahoe/urls.py
from django.urls import path, include
from django.views.generic.base import View
from .views import edit, dashboard, home, register
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)

app_name = 'mahoe'

urlpatterns = [
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', home, name='home'),
    path('login/', LoginView.as_view(template_name='mahoe/templates/authapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='mahoe/templates/authapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='mahoe/templates/authapp/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='mahoe/templates/authapp/password_change_done.html'),
         name='password_change_done'),
]

app/src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('mahoe.urls', namespace='mahoe')),
    path('admin/', admin.site.urls),
]

app/mahoe/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

class Wallet(models.Model):
    moneyAmount = models.FloatField(default=200.00)

class PurchaseHistory(models.Model):
    purchase_price = models.FloatField()
    date = models.DateTimeField()
    amount = models.FloatField()
    spendedCash = models.FloatField()
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=25)
    wallet = models.ForeignKey(to=Wallet, on_delete=models.CASCADE)

class OwnedCoin(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=25)
    amount = models.FloatField()
    purchase_price = models.FloatField()
    wallet = models.ForeignKey(to=Wallet, on_delete=models.CASCADE)

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    objects = UserManager()
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(
        verbose_name='first name',
        max_length=255,
    )
    last_name = models.CharField(
        verbose_name='last address',
        max_length=255,
    )
    username = models.CharField(
        verbose_name='username',
        max_length=255,
        unique=True
    )
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = [first_name, last_name, username]

    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

app/mahoe/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Usuário', widget=forms.TextInput)
    first_name = forms.CharField(label='Nome', widget=forms.TextInput)
    last_name = forms.CharField(label='Sobrenome', widget=forms.TextInput)
    email = forms.EmailField(label='Email', widget=forms.EmailInput)
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repita Senha', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("username is taken")
        return username

    def clean_password2(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password is not None and password != password2:
            self.add_error("password22", "Your passwords must match")
        return cleaned_data

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

app/mahoe/views.py
from django.http import request
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm, UserEditForm
import urllib.request
import json

def home(request):
    # prices
    price_request = urllib.request.urlopen("https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,BCH,EOS,LTC,XLM,ADA,USDT,MIOTA,TRX&tsyms=BRL")
    price = json.load(price_request)
    # news
    news_request = urllib.request.urlopen("https://min-api.cryptocompare.com/data/v2/news/?lang=PT")
    news = json.load(news_request)
    news['Data'] = news['Data'][:12]
    return render(request, 'home.html', {'news': news, 'price': price})

@login_required
def dashboard(request):
    context = {
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'mahoe/templates/authapp/dashboard.html', context=context)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'mahoe/templates/authapp/register_done.html')
    else:
        form = RegisterForm()

    context = {
        "form": form
    }

    return render(request, 'mahoe/templates/authapp/register.html', context=context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'mahoe/templates/authapp/edit.html', context=context)

app/mahoe/templates/authapp/dashboard.html
{% extends "base.html" %}
{% block title %} - Dashboard{% endblock title %}
{% block content %}
<h1>{{welcome}}</h1>
<br>
<a href="{% url 'mahoe:edit' %}" class="btn btn-primary">Edit Your Profile</a> or
<a href="{% url 'mahoe:password_change' %}" class="btn btn-warning">Change your password</a>
<hr>
{% endblock content %}

app/mahoe/templates/authapp/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

app/mahoe/templates/authapp/logged_out.html
{% extends "base.html" %}
{% block title %}- Sair{% endblock %}
{% block content %}
<h1>Logged out</h1>
<p>
    You have been successfully logged out.
    <hr>
    You can <a href="{% url 'mahoe:login' %}">log-in again</a>.
</p>
{% endblock %}

app/mahoe/templates/authapp/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %} - Entrar{% endblock title %}

{% block content %}
<div class="">
    <div style="text-align: center;">
        <h1>Entrar</h1>
        {% if form.errors %}
        <p>
            Usuário e/ou senha inválidos
        </p>
        {% endif %}
    </div>

    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <input type="hidden" name="next" value="{{ next }}" />
        <button type="submit" class="btn btn-primary">Entrar</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

app/mahoe/templates/authapp/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Change Your Password</h2>
<p>Use the form below to change your Password</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

app/mahoe/templates/authapp/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}- Cadastro

{% endblock title %}
{% block content %}

{% if form.errors %}

{% endif %}

<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Cadastrar</button>
    {% endbuttons %}
</form>
{% endblock content %}

app/mahoe/templates/authapp/register_done.html
{% extends "base.html" %}
{% block content %}
<h1>Bem-vindo {{ new_user.name }}!</h1>
<p>Cadastro realizado com sucesso. Clique <a href="{% url 'mahoe:login' %}">aqui</a> para realizar o login.</p>
{% endblock content %}

app/mahoe/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Mahoe {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
        </script>


</body>

</html>

app/mahoe/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Bem Vindo Ao Mahoe</h1>
  <p class="lead">Cadastre-se em nossa plataforma e obtenha R$200,00 para comprar qualquer crypto!</p>

</div>
<br />

<table class="table table-striped table-bordered table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">Nome </th>
      <th scope="col">Preço</th>
      <th scope="col">Máximo em 24h</th>
      <th scope="col">Mínimo em 24h</th>
      <th scope="col">Valor em Mercado</th>
    </tr>
  </thead>
  <tbody>
    {% for key,value in price.DISPLAY.items %}


    <tr>
      <td>{{ key }}</td>
      <td>{{ value.BRL.PRICE }}</td>
      <td>{{ value.BRL.HIGHDAY }}</td>
      <td>{{ value.BRL.LOWDAY }}</td>
      <td>{{ value.BRL.MKTCAP }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>

<br /><br />

<div class="container">
  <div class="row">
    {% for x in news.Data %}
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{ x.imageurl }}" alt="{{ x.source }}">
        <div class="card-body">
          <h5 class="card-title">{{ x.title }}</h5>
          <p class="card-text">{{ x.body|slice:"200" }}...</p>
          <a href="{{ x.url }}" class="btn btn-secondary">Read More...</a>
        </div>
      </div>
      <br />
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

app/mahoe/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'mahoe:home' %}">Mahoe <i class="fab fa-bitcoin"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Moedas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Carteira</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mahoe:dashboard' %}">Perfil <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% endif %}
        <span style="margin-inline-start: auto;">
            {% if request.user.is_authenticated %}
            Olá, <i>{{user.username}}</i>
            <a href="{% url 'mahoe:logout' %}" class="btn btn-danger">Logout</a>
            {% else %}
            <div class="login__left">
                <a href="{% url 'mahoe:login' %}" class="btn btn-secondary">Entrar</a>
                <a href="{% url 'mahoe:register' %}" class="btn btn-info ">Cadastrar</a>
            </div>

            {% endif %}

        </span>
    </div>
</nav>